export const FETCH_CLASSES_REQUEST = 'FETCH_CLASSES_REQUEST'
export const FETCH_CLASSES_REQUEST_SUCCESS = 'FETCH_CLASSES_REQUEST_SUCCESS'
export const FETCH_CLASSES_REQUEST_ERROR = 'LOAD_CLASSES_ERROR'

export const SELECTED_CLASS = 'SELECTED_CLASS'
export const ATTENDANCE_DATE_TIME = 'ATTENDANCE_DATE_TIME'

export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST'
export const FETCH_STUDENTS_REQUEST_SUCCESS = 'FETCH_STUDENTS_REQUEST_SUCCESS'
export const FETCH_STUDENTS_REQUEST_ERROR = 'FETCH_STUDENTS_REQUEST_ERROR'

export const SELECTED_ATTENDANCE = 'SELECTED_ATTENDANCE'