export const FETCH_CLASSES_REQUEST = 'FETCH_CLASSES_REQUEST';
export const FETCH_CLASSES_REQUEST_SUCCESS = 'FETCH_CLASSES_REQUEST_SUCCESS';
export const FETCH_CLASSES_REQUEST_ERROR = 'LOAD_CLASSES_ERROR';
export const SELECTED_CLASS = 'SELECTED_CLASS';

export const FETCH_SUBJECTS_REQUEST = 'FETCH_SUBJECTS_REQUEST';
export const FETCH_SUBJECTS_REQUEST_SUCCESS = 'FETCH_SUBJECTS_REQUEST_SUCCESS';
export const FETCH_SUBJECTS_REQUEST_ERROR = 'LOAD_SUBJECTS_ERROR';
export const SELECTED_SUBJECT = 'SELECTED_SUBJECT';

export const ATTENDANCE_DATE_TIME = 'ATTENDANCE_DATE_TIME';

export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_REQUEST_SUCCESS = 'FETCH_STUDENTS_REQUEST_SUCCESS';
export const FETCH_STUDENTS_REQUEST_ERROR = 'FETCH_STUDENTS_REQUEST_ERROR';

export const SELECTED_ATTENDANCE = 'SELECTED_ATTENDANCE';

/* 
export const SUBMIT_ATTENDANCE_REQUEST = 'SUBMIT_ATTENDANCE_REQUEST';
export const SUBMIT_ATTENDANCE_REQUEST_SUCCESS =
    'SUBMIT_ATTENDANCE_REQUEST_SUCCESS';
export const SUBMIT_ATTENDANCE_REQUEST_ERROR =
    'SUBMIT_ATTENDANCE_REQUEST_ERROR'; 
*/

export const SET_RECENT_ATTENDANCES = 'SET_RECENT_ATTENDANCES';
